dist: trusty
sudo: required 
language: cpp
os:
- linux
branches:
  only:
  - master
env:
  global:
  - GOOGLETEST_HOME=$TRAVIS_BUILD_DIR/lib/googletest

script:
- cd $TRAVIS_BUILD_DIR/ci/travis;
  ./install_googletest.sh;
- cd $TRAVIS_BUILD_DIR/ci/travis;
  ./build_library.sh;
- cd $TRAVIS_BUILD_DIR/ci/travis;
  ./build_client1.sh;
- cd $TRAVIS_BUILD_DIR/ci/travis;
  ./build_client2.sh;
- cd $TRAVIS_BUILD_DIR/ci/travis;
  ./build_client3.sh;
- cd $TRAVIS_BUILD_DIR/build/bin;
  ./footest || true; #do not fail build even if a test fails.

after_success:
- echo AFTER SUCCESS!

notifications:
  email: true
